Setup the calculator UI
GiuseppeTG/Calculator pull request #2
Opened 2022-06-28 22:51 UTC by GiuseppeTG

### Requirements 

- Delete all the boilerplate from CRA (text, images, styles).
- Create a directory called components.
- Inside components, create a new Calculator.js file.
- In Calculator.js, create a React component that matches this design:
- Don't add any extra design.
- Develop just the UI of the calculator; the math logic to make it work will be added in the next project.
- Use class-based components (All components should be class-based).
- Once the Calculator is ready, import it and use it in your main component (App.js).
- Test it in the browser; it should render without problems.

2022-06-28 22:57 UTC, GiuseppeTG commented
I did not delete the testing files that create-react-app creates. If I'm not wrong, we are going to use them later.

2022-06-28 23:04 UTC, DammyShittu requested changes
Hi @GiuseppeTG,

✔️ Calculator matches wireframe

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-28 23:04 UTC, DammyShittu commented on README.md
> +![](https://img.shields.io/badge/Microverse-blueviolet)
- [ ] I don't think these boilerplate files would be relevant to this project. To keep the codebase clean, I would recommend you remove them and resolve resulting import issues.

  ![giuseppe-src](https://user-images.githubusercontent.com/54848363/176318405-43ab3104-b2fe-4b75-8ffd-5e1235fe09fa.jpg)

2022-06-29 01:47 UTC, Davidosky007 approved these changes
Hi @GiuseppeTG 👋 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![approved-stamp](https://user-images.githubusercontent.com/52497246/176333441-70b27e7a-98ad-448b-8327-aa8c6bb2ef53.gif)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-30 03:57 UTC, merged